<?php

namespace App\Filament\Resources\Materials\Schemas;

use App\Enums\PublishStatus;
use App\Filament\Support\AdminOptions;
use App\Filament\Support\AdminUploadStorage;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;
use Illuminate\Support\Str;

class MaterialForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make(__('admin.ui.material_settings'))
                    ->schema([
                        Grid::make(2)
                            ->schema([
                                TextInput::make('slug')
                                    ->required()
                                    ->maxLength(255)
                                    ->unique(ignoreRecord: true),
                                Select::make('status')
                                    ->label(__('admin.fields.status'))
                                    ->options(PublishStatus::options())
                                    ->required()
                                    ->default(PublishStatus::Draft->value),
                                Toggle::make('is_featured')
                                    ->required(),
                                TextInput::make('sort_order')
                                    ->label(__('admin.ui.sort_order'))
                                    ->required()
                                    ->numeric()
                                    ->default(0),
                                self::mediaUpload('cms/materials'),
                                TextInput::make('media_url')
                                    ->label(__('admin.ui.external_media_url'))
                                    ->url(),
                                DateTimePicker::make('published_at')
                                    ->label(__('admin.ui.published_at')),
                            ]),
                    ]),
                Section::make(__('admin.ui.english'))
                    ->schema([
                        TextInput::make('title_translations.en')
                            ->label(__('admin.ui.title'))
                            ->required()
                            ->live(onBlur: true)
                            ->afterStateUpdated(function (Set $set, ?string $state): void {
                                $set('slug', Str::slug((string) $state));
                            }),
                        TextInput::make('headline_translations.en')
                            ->label(__('admin.ui.headline')),
                        Textarea::make('summary_translations.en')
                            ->label(__('admin.ui.summary'))
                            ->columnSpanFull(),
                        Textarea::make('story_overview_translations.en')
                            ->label(__('admin.ui.story_overview'))
                            ->columnSpanFull(),
                        Textarea::make('science_overview_translations.en')
                            ->label(__('admin.ui.science_overview'))
                            ->columnSpanFull(),
                    ]),
                Section::make(__('admin.ui.korean'))
                    ->schema([
                        TextInput::make('title_translations.ko')
                            ->label(__('admin.ui.title')),
                        TextInput::make('headline_translations.ko')
                            ->label(__('admin.ui.headline')),
                        Textarea::make('summary_translations.ko')
                            ->label(__('admin.ui.summary'))
                            ->columnSpanFull(),
                        Textarea::make('story_overview_translations.ko')
                            ->label(__('admin.ui.story_overview'))
                            ->columnSpanFull(),
                        Textarea::make('science_overview_translations.ko')
                            ->label(__('admin.ui.science_overview'))
                            ->columnSpanFull(),
                    ]),
                Section::make(__('admin.ui.chinese'))
                    ->schema([
                        TextInput::make('title_translations.zh')
                            ->label(__('admin.ui.title')),
                        TextInput::make('headline_translations.zh')
                            ->label(__('admin.ui.headline')),
                        Textarea::make('summary_translations.zh')
                            ->label(__('admin.ui.summary'))
                            ->columnSpanFull(),
                        Textarea::make('story_overview_translations.zh')
                            ->label(__('admin.ui.story_overview'))
                            ->columnSpanFull(),
                        Textarea::make('science_overview_translations.zh')
                            ->label(__('admin.ui.science_overview'))
                            ->columnSpanFull(),
                    ]),
                Section::make(__('admin.ui.certifications_technical_evidence'))
                    ->description(__('admin.ui.publish_only_confirmed_data_mark_unapproved_records_as_pending_in_test_a077be01c5'))
                    ->schema([
                        Repeater::make('certifications')
                            ->label(__('admin.ui.certifications_and_tests'))
                            ->addActionLabel(__('admin.ui.add_certification_or_test'))
                            ->collapsible()
                            ->reorderableWithButtons()
                            ->defaultItems(0)
                            ->schema([
                                TextInput::make('key')
                                    ->label(__('admin.ui.internal_key'))
                                    ->maxLength(120),
                                TextInput::make('name')
                                    ->label(__('admin.ui.certification_test_name'))
                                    ->required()
                                    ->maxLength(180),
                                TextInput::make('label')
                                    ->label(__('admin.ui.display_label'))
                                    ->maxLength(180),
                                Select::make('status')
                                    ->label(__('admin.fields.status'))
                                    ->options(fn (): array => AdminOptions::certificationStatuses())
                                    ->required()
                                    ->default('pending'),
                                Toggle::make('verified')
                                    ->label(__('admin.ui.verified'))
                                    ->helperText(__('admin.ui.only_enable_when_a_final_approved_evidence_record_exists')),
                                TextInput::make('value')
                                    ->label(__('admin.ui.display_value'))
                                    ->maxLength(120),
                                TextInput::make('result')
                                    ->label(__('admin.ui.value_result'))
                                    ->maxLength(120),
                                TextInput::make('unit')
                                    ->label(__('admin.ui.unit'))
                                    ->maxLength(40),
                                TextInput::make('issuer')
                                    ->label(__('admin.ui.issuing_body_lab'))
                                    ->maxLength(180)
                                    ->helperText(__('admin.ui.use_client_confirmation_pending_when_a_lab_is_not_approved_for_publication')),
                                DatePicker::make('tested_at')
                                    ->label(__('admin.ui.test_date')),
                                TextInput::make('document_url')
                                    ->label(__('admin.ui.document_url'))
                                    ->url()
                                    ->maxLength(2048),
                                Textarea::make('description')
                                    ->label(__('admin.ui.description'))
                                    ->rows(3)
                                    ->columnSpanFull(),
                                TextInput::make('label_translations.en')
                                    ->label(__('admin.ui.label_en')),
                                TextInput::make('value_translations.en')
                                    ->label(__('admin.ui.value_en')),
                                TextInput::make('label_translations.ko')
                                    ->label(__('admin.ui.label_ko')),
                                TextInput::make('value_translations.ko')
                                    ->label(__('admin.ui.value_ko')),
                                TextInput::make('label_translations.zh')
                                    ->label(__('admin.ui.label_zh')),
                                TextInput::make('value_translations.zh')
                                    ->label(__('admin.ui.value_zh')),
                            ])
                            ->columns(2)
                            ->columnSpanFull(),
                        Repeater::make('technical_downloads')
                            ->label(__('admin.ui.technical_downloads'))
                            ->addActionLabel(__('admin.ui.add_download'))
                            ->collapsible()
                            ->reorderableWithButtons()
                            ->defaultItems(0)
                            ->schema([
                                TextInput::make('title')
                                    ->label(__('admin.ui.title'))
                                    ->required()
                                    ->maxLength(180),
                                Select::make('type')
                                    ->label(__('admin.fields.type'))
                                    ->options(fn (): array => AdminOptions::technicalDownloadTypes())
                                    ->required(),
                                Select::make('status')
                                    ->label(__('admin.fields.status'))
                                    ->options(fn (): array => AdminOptions::technicalDownloadStatuses())
                                    ->default('on_request')
                                    ->required(),
                                TextInput::make('url')
                                    ->label(__('admin.ui.file_url'))
                                    ->url()
                                    ->maxLength(2048),
                                Textarea::make('description')
                                    ->label(__('admin.ui.description'))
                                    ->rows(3)
                                    ->columnSpanFull(),
                            ])
                            ->columns(2)
                            ->columnSpanFull(),
                    ]),
                Section::make(__('admin.ui.specifications'))
                    ->description(__('admin.ui.structured_attributes_shown_on_material_detail_pages'))
                    ->schema([
                        Repeater::make('specs')
                            ->relationship()
                            ->label(__('admin.ui.specifications'))
                            ->addActionLabel(__('admin.ui.add_specification'))
                            ->orderColumn('sort_order')
                            ->reorderableWithButtons()
                            ->collapsible()
                            ->defaultItems(0)
                            ->schema([
                                Grid::make(2)
                                    ->schema([
                                        TextInput::make('key')
                                            ->label(__('admin.ui.internal_key'))
                                            ->maxLength(120),
                                        TextInput::make('unit')
                                            ->label(__('admin.ui.unit'))
                                            ->maxLength(40),
                                        TextInput::make('icon')
                                            ->label(__('admin.ui.icon'))
                                            ->maxLength(120),
                                        Select::make('status')
                                            ->label(__('admin.fields.status'))
                                            ->options(PublishStatus::options())
                                            ->required()
                                            ->default(PublishStatus::Draft->value),
                                        self::mediaUpload('cms/material-specs'),
                                        TextInput::make('media_url')
                                            ->label(__('admin.ui.external_media_url'))
                                            ->url(),
                                    ]),
                                TextInput::make('label_translations.en')
                                    ->label(__('admin.ui.label_en'))
                                    ->required(),
                                TextInput::make('value_translations.en')
                                    ->label(__('admin.ui.value_en'))
                                    ->required(),
                                Textarea::make('detail_translations.en')
                                    ->label(__('admin.ui.detail_en'))
                                    ->columnSpanFull(),
                                TextInput::make('label_translations.ko')
                                    ->label(__('admin.ui.label_ko')),
                                TextInput::make('value_translations.ko')
                                    ->label(__('admin.ui.value_ko')),
                                Textarea::make('detail_translations.ko')
                                    ->label(__('admin.ui.detail_ko'))
                                    ->columnSpanFull(),
                                TextInput::make('label_translations.zh')
                                    ->label(__('admin.ui.label_zh')),
                                TextInput::make('value_translations.zh')
                                    ->label(__('admin.ui.value_zh')),
                                Textarea::make('detail_translations.zh')
                                    ->label(__('admin.ui.detail_zh'))
                                    ->columnSpanFull(),
                            ])
                            ->columns(2)
                            ->columnSpanFull(),
                    ]),
                Section::make(__('admin.ui.story_sections_2'))
                    ->description(__('admin.ui.narrative_sections_used_across_the_material_storytelling_page'))
                    ->schema([
                        Repeater::make('storySections')
                            ->relationship()
                            ->label(__('admin.ui.story_sections'))
                            ->addActionLabel(__('admin.ui.add_story_section'))
                            ->orderColumn('sort_order')
                            ->reorderableWithButtons()
                            ->collapsible()
                            ->defaultItems(0)
                            ->schema([
                                Grid::make(2)
                                    ->schema([
                                        TextInput::make('highlight')
                                            ->label(__('admin.ui.default_highlight'))
                                            ->maxLength(255),
                                        Select::make('status')
                                            ->label(__('admin.fields.status'))
                                            ->options(PublishStatus::options())
                                            ->required()
                                            ->default(PublishStatus::Draft->value),
                                        self::mediaUpload('cms/material-story-sections'),
                                        TextInput::make('media_url')
                                            ->label(__('admin.ui.external_media_url'))
                                            ->url(),
                                    ]),
                                TextInput::make('title_translations.en')
                                    ->label(__('admin.ui.title_en'))
                                    ->required(),
                                TextInput::make('subtitle_translations.en')
                                    ->label(__('admin.ui.subtitle_en')),
                                Textarea::make('content_translations.en')
                                    ->label(__('admin.ui.content_en'))
                                    ->required()
                                    ->columnSpanFull(),
                                TextInput::make('highlight_translations.en')
                                    ->label(__('admin.ui.highlight_en')),
                                TextInput::make('title_translations.ko')
                                    ->label(__('admin.ui.title_ko')),
                                TextInput::make('subtitle_translations.ko')
                                    ->label(__('admin.ui.subtitle_ko')),
                                Textarea::make('content_translations.ko')
                                    ->label(__('admin.ui.content_ko'))
                                    ->columnSpanFull(),
                                TextInput::make('highlight_translations.ko')
                                    ->label(__('admin.ui.highlight_ko')),
                                TextInput::make('title_translations.zh')
                                    ->label(__('admin.ui.title_zh')),
                                TextInput::make('subtitle_translations.zh')
                                    ->label(__('admin.ui.subtitle_zh')),
                                Textarea::make('content_translations.zh')
                                    ->label(__('admin.ui.content_zh'))
                                    ->columnSpanFull(),
                                TextInput::make('highlight_translations.zh')
                                    ->label(__('admin.ui.highlight_zh')),
                            ])
                            ->columns(2)
                            ->columnSpanFull(),
                    ]),
                Section::make(__('admin.ui.applications'))
                    ->description(__('admin.ui.audience_specific_use_cases_and_call_to_action_blocks_for_the_material'))
                    ->schema([
                        Repeater::make('applications')
                            ->relationship()
                            ->label(__('admin.ui.applications'))
                            ->addActionLabel(__('admin.ui.add_application'))
                            ->orderColumn('sort_order')
                            ->reorderableWithButtons()
                            ->collapsible()
                            ->defaultItems(0)
                            ->schema([
                                Grid::make(2)
                                    ->schema([
                                        TextInput::make('cta_url')
                                            ->label(__('admin.ui.cta_url'))
                                            ->url(),
                                        Select::make('status')
                                            ->label(__('admin.fields.status'))
                                            ->options(PublishStatus::options())
                                            ->required()
                                            ->default(PublishStatus::Draft->value),
                                        self::mediaUpload('cms/material-applications'),
                                        TextInput::make('media_url')
                                            ->label(__('admin.ui.external_media_url'))
                                            ->url(),
                                    ]),
                                TextInput::make('title_translations.en')
                                    ->label(__('admin.ui.title_en'))
                                    ->required(),
                                TextInput::make('subtitle_translations.en')
                                    ->label(__('admin.ui.subtitle_en')),
                                TextInput::make('audience_translations.en')
                                    ->label(__('admin.ui.audience_en')),
                                TextInput::make('cta_label_translations.en')
                                    ->label(__('admin.ui.cta_label_en')),
                                Textarea::make('description_translations.en')
                                    ->label(__('admin.ui.description_en'))
                                    ->required()
                                    ->columnSpanFull(),
                                TextInput::make('title_translations.ko')
                                    ->label(__('admin.ui.title_ko')),
                                TextInput::make('subtitle_translations.ko')
                                    ->label(__('admin.ui.subtitle_ko')),
                                TextInput::make('audience_translations.ko')
                                    ->label(__('admin.ui.audience_ko')),
                                TextInput::make('cta_label_translations.ko')
                                    ->label(__('admin.ui.cta_label_ko')),
                                Textarea::make('description_translations.ko')
                                    ->label(__('admin.ui.description_ko'))
                                    ->columnSpanFull(),
                                TextInput::make('title_translations.zh')
                                    ->label(__('admin.ui.title_zh')),
                                TextInput::make('subtitle_translations.zh')
                                    ->label(__('admin.ui.subtitle_zh')),
                                TextInput::make('audience_translations.zh')
                                    ->label(__('admin.ui.audience_zh')),
                                TextInput::make('cta_label_translations.zh')
                                    ->label(__('admin.ui.cta_label_zh')),
                                Textarea::make('description_translations.zh')
                                    ->label(__('admin.ui.description_zh'))
                                    ->columnSpanFull(),
                            ])
                            ->columns(2)
                            ->columnSpanFull(),
                    ]),
            ]);
    }

    private static function mediaUpload(string $directory): FileUpload
    {
        return FileUpload::make('media_path')
            ->label(__('admin.ui.uploaded_media'))
            ->image()
            ->disk(fn (): string => AdminUploadStorage::disk())
            ->directory($directory)
            ->visibility(fn (): string => AdminUploadStorage::visibility());
    }
}
